version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: user-management-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - user-management-network
    depends_on:
      - app

  app:
    build:
      args:
        user: Shakil
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: user-management
    container_name: user-management
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html:cached
    networks:
      - user-management-network
    depends_on:
      - database

  database:
    image: mariadb:10.5.8
    container_name: user-management-mariadb
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - user-management-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=@@@2083
      - MYSQL_USER=root
      - MYSQL_PASSWORD=@@@2083
      - MYSQL_DATABASE=user_management
    networks:
      - user-management-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: user-management-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - database
    ports:
      - '9000:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '@@@2083'
    networks:
      - user-management-network

networks:
  user-management-network:
    driver: bridge

volumes:
  user-management-volume:
    driver: local
